spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:13306/default
    username: root
    password: 1234
  redis:
    host: localhost
    port: 16379